language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2
    
before_install:
  - chmod +x mvnw
  
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - turboguy36@gmail.com 

before_deploy:
  - zip -r springboot-swagger *
  - mkdir -p deploy
  - mv springboot-swagger.zip deploy/springboot-swagger.zip
  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-deploy-storage # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    cleanup: true
    acl: public_read
    wait_until_deployed: true
    on:
      repo: quirinal36/SpringBootDBConnected #Github 주소
      branch: master
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-deploy-storage # 6-3-3에서 생성한 S3 버킷
    key: springboot-swagger.zip
    bundle_type: zip
    application: springboot-swagger
    deployment_group: SpringBootSwaggerGroup
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      repo: quirinal36/SpringBootDBConnected #Github 주소
      branch: master