version: '2'

services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: jca
      MYSQL_USER: leehg
      MYSQL_PASSWORD: 789gagul
    ports:
      - 3306:3306

  tomcat:
    image: 'docker.io/bitnami/tomcat:9.0-debian-10'
    environment:
      JDBC_URL: jdbc:mysql://db:3306/jca
      JDBC_USER: leehg
      JDBC_PASS: 789gagul
    links:
      - db
    volumes:
      - 'tomcat_data:/bitnami'
    restart:
      always
    build:
      context: .
      dockerfile : Dockerfile-tomcat
    ports:
      - "80:8080"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  redis:
    image: redis
    command: redis-server --requirepass changeme --port 6379
    restart: always
    ports:
      - 6379:6379
  jenkins:
    image: 'jenkins/jenkins:latest'
    container_name: 'jenkins'
    restart: always
    ports:
      - '8100:8080'
      - '50100:50000'
    expose:
      - '8080'
      - '50000'
    volumes:
      - './jenkins_home:/var/jenkins_home'
    environment:
      TZ: "Asia/Seoul"
volumes:
  tomcat_data:
    driver: local
