version: '3'

services:
  db:
    image: mariadb
    container_name: 'mariadb'
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: jca
      MYSQL_USER: leehg
      MYSQL_PASSWORD: 789gagul
    ports:
      - 33000:3306
    expose:
      - 33000

  redis:
    image: redis
    container_name: 'redis'
    command: redis-server --requirepass changeme --port 6379
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
      
  tomcat:
    image: tomcat:9
    container_name: 'tomcat'
    environment:
      JDBC_URL: jdbc:mysql://db:3306/jca
      JDBC_USER: leehg
      JDBC_PASS: 789gagul
    links:
      - db
      - redis
    ports:
      - '80:8080'
    volumes:
      - 'tomcat_data:/usr/local/tomcat/webapps/'
    restart:
      always

volumes:
  tomcat_data:
    driver: local
  db-data:
    driver: local