
version: '3.1'

services:

  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: khub9072
    ports:
      - 3306:3306

  tomcat:
    image: tomcat
    environment:
      - "JAVA_OPTS=-Dspring.profiles.active=dev"
    build:
      context: .
      dockerfile : Dockerfile-tomcat
    ports:
      - "80:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps/
    links:
      - db
    restart: always  
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  redis:
    image: redis
    command: redis-server --requirepass changeme --port 6379
    restart: always
    ports:
      - 6379:6379