jwt:
    access:
        token:
            expire:
                time: 5
            secure:
                key: solasido
    get:
        access:
            token:
                url: /api/v1/get_access_token
    refresh:
        token:
            expire:
                time: 60
            secure:
                key: domisola
mybatis:
    mapper-locations: mapper/**/*.xml
    type-aliases-package: com.example.demo.model
server:
    port: 8080
spring:
    cache:
        type: redis
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 4
        password: 789gagul
        url: jdbc:mysql://db:3306/jca?useSSL=false&verifyServerCertificate=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: leehg
    profile:
        value: dev
    redis:
        host: redis
        password: changeme
        port: 6379
    thymeleaf:
        cache: false
        check-template-location: true
        mode: HTML
        order: 0
        prefix: classpath:templates/
        suffix: .html
